// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8uOlMO1Z4N12NjYO6RCIZyi7qSXGffuY',
    appId: '1:123025542189:web:8315fee66237138aa23ca4',
    messagingSenderId: '123025542189',
    projectId: 'tawelty-app',
    authDomain: 'tawelty-app.firebaseapp.com',
    storageBucket: 'tawelty-app.firebasestorage.app',
    measurementId: 'G-108DDTXRLK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNwsTG1GE9xmGB_48Ok4eCgnEmiG2SKT8',
    appId: '1:123025542189:android:daa7e5fd136e1368a23ca4',
    messagingSenderId: '123025542189',
    projectId: 'tawelty-app',
    storageBucket: 'tawelty-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtpmtDHiRw_--VVvKV42qGAE2s_hSGbO4',
    appId: '1:123025542189:ios:201b2ef357b4d81ca23ca4',
    messagingSenderId: '123025542189',
    projectId: 'tawelty-app',
    storageBucket: 'tawelty-app.firebasestorage.app',
    iosBundleId: 'com.example.taweltyApp',
  );
}
